### ISSUE TITLE
Download link point to 404

### ISSUE THREAD

**Issue by dueksam** [BBasile/Coedit#1]
Hey,

I wanted to try this IDE but the download link in the readme is dead : https://github.com/BBasile/Coedit/releases/download/1_update_2/coedit.1update2.win32.setup.zip

There's nothing but the source code available in the 'releases'.

Sam

**Comment by BBasile** [comment]
Yes, I know, this is because CE is just replublished. GH always recreate the links to download the tarballs from the git tags but the builds were done by me.

So either you have to [build it yourself](https://github.com/BBasile/Coedit/wiki#build-the-sources) with FPC 2.64 and Lazarus 1.4.4 (see the wiki), or wait for the next release (2.a3).

**Comment by BBasile** [comment]
A new release is available, with setup program or pre-built binaries. Note that old links found elsewhere (Dlang NG archive or HN or wherever) will still be broken.
