### ISSUE TITLE
Very strange, obvious errors in "ce_symstring.pas" that break the build...

### ISSUE THREAD

**Issue by BenGrasset** [BBasile/Coedit#10]
For example, at line 191:

fSymbols[CPP] := fSymbols[CPF].extractFilePath;

I don't understand how someone good enough at Pascal to develop this IDE could possibly think this would ever work? Since when do **strings** have RTL methods as properties? Not to be rude, but **what** were you thinking? Clearly this should be:

fSymbols[CPP] := ExtractFilePath(fSymbols[CPF]);

There are several other instances of similiar mistakes in the file (all attempts to use "Extract" methods as string properties)

**Comment by BBasile** [comment]
It's type helpers. It only works since FPC 3.0.0:

```Pascal
program demo;
{$MODESWITCH TYPEHELPERS}

type TStringHelper = type helper for string
  function dblQuote: string;
end;

function TStringHelper.dblQuote: string;
begin
  exit('"' + self + '"');
end;

begin
  writeln('FPC-type-helper'.dblQuote);
end.
```

outputs:

> "FPC-type-helper"

- read more here: http://wiki.freepascal.org/FPC_New_Features_3.0#Support_for_type_helpers
- and Coedit helper for strings is [here](https://github.com/BBasile/Coedit/blob/master/src/ce_common.pas#L52-L61)

If you can't manage to build Coedit this is because you need FPC 3.0.0 + Lazarus 1.6 (currently unreleased):

- [nix rpm](http://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20x86_64%20RPM/Lazarus%201.6RC2/)
- [win 32 setup](http://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2032%20bits/Lazarus%201.6RC2/)

Sorry I'm a little ahead with this feature.

**Comment by BBasile** [comment]
Do you mind If I quote this message in a forum ? (not your real name, OK ?). Your Q is actually very symptomatic of how FPC is not well advertised.

**Comment by BenGrasset** [comment]
I'm aware of type helpers, actually. Perhaps I should have searched the source directory for instances of "Extract" to see if it was something you'd created yourself before posting this though, haha. That being said, I'm running trunk FPC and trunk Lazarus and it still didn't build. Is the {$MODESWITCH TYPEHELPERS} flag actually defined anywhere in the project?

**Comment by BenGrasset** [comment]
Ok, figured it out. I had to move the inclusion of "ce_common" down from the first uses list to the second one, after "implementation". I have no idea why, but it works now. Some sort of internal unit hierarchy thing in FPC, maybe?

**Comment by BBasile** [comment]
Theorically this kind of things shouldn't change (order of unit because of init  fina of a unit), maybe FPC trunk is broken.

**Comment by BBasile** [comment]
ragarde ca Maud, moi aussi je suis confronté à des gros cons qui se la pète. Dans le genre [Duning Kruger](https://fr.wikipedia.org/wiki/Effet_Dunning-Kruger) on fait pas mieux.
