### ISSUE TITLE
dub support

### ISSUE THREAD

**Issue by Extrawurst** [BBasile/Coedit#10]
opening a dub.json project description should be supported like it is in mono-d, since dub is about to be bundled with dmd soon

**Comment by BBasile** [comment]
***call to idea for the DUB project editor widget !***

The *DUB* integration has started. A priori, the *DUB project editor widget* is going to be a basic tree with a common property editor for each tree node. In a toolbar: *'add property'* and *'remove property'*. Maybe some stuff to avoid errors (detect if a new prop name is not related to DUB, check values, etc...)
At the top (not yet visible in the preview): a file list, a config selector (like the project inspector).

However since as a *D* user I almost don't use *DUB* I'll probably miss out some important features that a regular *DUB-er* would require. If you (by *you* I mean any follower, this is global call) think that the widget is already going in the wrong direction, please tell it, suggest any better idea or discuss about how the widget should looks.

preview:
![dubprojecteditorwidget](https://cloud.githubusercontent.com/assets/7805501/9698803/bc8dcdfa-53c6-11e5-952e-96c6eb0ee820.png)

**Comment by BBasile** [comment]
It's still time to get involved because the widget begins to have its particular little style, after it'll be too late...:zzz:
![step2](https://cloud.githubusercontent.com/assets/7805501/9723345/603f9434-55bf-11e5-9a19-f6e7a0a345a6.png)

**Comment by BBasile** [comment]
DUB support is at 82.678%

- All the project menu items works (compile, run, run with args, view project files, etc)
- DCD works on the whole project definition (sources, imports)
- Editor is almost finished:

    - select a config. in coedit configs and build type are combined in a list:

    ![conf](https://cloud.githubusercontent.com/assets/7805501/9957847/067b5e22-5e04-11e5-89a9-e1b0908a8e8c.png)

    - source list can be filtered, double click an item to open in editor:

    ![files_filter](https://cloud.githubusercontent.com/assets/7805501/9957872/2f6ca296-5e04-11e5-9d9d-e6e7c4c3ea85.png)

    - properties can be edited in a second tab. currently what's missing is adding new props:

    ![props](https://cloud.githubusercontent.com/assets/7805501/9957892/6ff676c0-5e04-11e5-8138-13be8836f15f.png)

Otherwise, some minor stuffs still miss:
- new project in menu: either native or dub.
- todo list, minor tweaks.

Maybe some global DUB options will be added (e.g always force rebuild, prefered compiler, etc). They would appear in the option editor, in a dedicated category.

Screen caps are done on dlangui json, which is a complex DUB project and is good to test the integration.

**2_alpha_1** will be focused on this feature. Even if now the global design can't be changed anymore it'll be still time to tweak some details.

**Comment by BBasile** [comment]
done, still need testing & bug fixing.
