### ISSUE TITLE
TStringHelper - Identifier not found

### ISSUE THREAD

**Issue by XuTpuK** [BBasile/Coedit#111]
I build coedit on ArchLinux x64, FPC=3.0.0-1
Compilation fails with error:
ce_common.pas(70,46) Error: (5000) Identifier not found "TStringHelper"
ce_common.pas(70,46) Error: (4009) class type expected, but got "&lt;erroneous type&gt;"

What can be problem?

**Comment by BBasile** [comment]
Since last week you need FPC 3.0.2, which is not officially released. See http://forum.lazarus.freepascal.org/index.php/topic,35267.msg232815.html#msg232815. Binaries are here: ftp://freepascal.stack.nl/pub/fpc/beta/3.0.2-rc1/. You need to replace the vinaries but also to add a new folder for the run-time library sources.
