### ISSUE TITLE
Some suggestions :)

### ISSUE THREAD

**Issue by RUSshy** [BBasile/Coedit#120]
Hello

This IDE is nice, but some features are missing in my opinion

* It would be nice to have same dark theme as IntellIJ IDEA
* A build and run button
* Import Suggestion popup like in IntelliJ IDEA
* Auto open code completion popup when i start to type instead of CTRL + SPACE
* complete code from completion when i press TAB

Thanks for your work, i use it when i need to work on d server

**Comment by BBasile** [comment]
> - It would be nice to have same dark theme as IntellIJ IDEA

If you talk about the editor then if you have the time to you can make the theme. Then send me the file named _highlighterPresets.txt_ so that i can add the scheme to the presets that are hardcoded in the application.

> - A build and run button

You have it in the _Compilation menu_. It's called _compile and run_. It can be done on the current file or on the project.

> - Import Suggestion popup like in IntelliJ IDEA

Please open an individual issue for this. If a time or another it gets done then it's better to auto close using the commit message.

> - Auto open code completion popup when i start to type instead of CTRL + SPACE
> - complete code from completion when i press TAB

Please open an individual issue for these two. If a time or another it gets done then it's better to auto close using the commit message.
