### ISSUE TITLE
Windows system COMPLETELY broken

### ISSUE THREAD

**Issue by LeComm** [BBasile/Coedit#13]
So I accidentally closed the source editor window. When clicking on windows -> source editor, it won't appear again; the Coedit window loses focus instead, but no new window appears. This bug also concerns the "Mini explorer", "Search replace" and "Tools editor" windows. I'm using Win7 and have installed Coedit on my local drive (though, the OS was telling me the installation was not successful, while the installer console said everything is fine).
Also, is there any quick workaround for this, maybe you can tell me where I can find the layout files so I can hack one until this bug is fixed?

**Comment by BBasile** [comment]
In the explorer, open

`?:\Users\<your account>\AppData\Roaming\Coedit`

and delete

`docking.xml`

The bug is known. Once you re happy with the layout, you can right click on the header of one of the widget and then activate **locked**. This prevents any accidental undocking.

![lock_layout](https://cloud.githubusercontent.com/assets/7805501/8088853/96c34d90-0fa4-11e5-9a79-550b955692ca.png)

This happens mostly with the code editor, as it's the central widget.
Read more in #4 .

**Comment by Scroph** [comment]
I ran into a similar problem earlier on Windows 7. A workaround would be to press ALT + space, this will display the contextual menu. Click on the "Move" (not sure if it's the right term as my Windows isn't in English, but it's the 2nd item on the list) item, press one of the arrow keys on your keyboard then move the cursor. The window show up out of nowhere and follow its movement.

**Comment by BBasile** [comment]
The problem is fixed in 568c229. I'll release 1_update_1 in Jully. In the meantime, don't close a docked widget using the button in the header. Instead: 
- in a first time right click the header, click the menu item _undock_. 
- then at this time, when it's undocked, you can close the widget.

This is really the best that can be done in Coedit 1. The problem is that the fixes i could make to the 3rd party component are only visible when the 3rd party component is itself released...so 3 times per year. Hopefully this is an open-source program so it could be even worst (not to name _D....i_ :speak_no_evil:)

**Comment by BBasile** [comment]
the fix is applied in version 1 update 1
