### ISSUE TITLE
Projects do not work

### ISSUE THREAD

**Issue by DenianArthurShades** [BBasile/Coedit#15]
Whenever I try to open or create a project (dub.json or native format doesn't matter), this happens:
* everything stays empty
* the sub-entries of "Configurations" in the project inspector vanish
* UI elements of project inspector and project configuration (buttons, filters,...) stop working

I can edit single files without a problem, but I don't need an IDE for that.

I'm trying to use Coedit on Win7 x64. Running as admin didn't fix the problem, either.

**Before trying to open a project**
![before](https://cloud.githubusercontent.com/assets/9946964/13087648/476b5fac-d4e9-11e5-842e-bffbf4c6eeb9.png)

**After trying to open a project**
![after](https://cloud.githubusercontent.com/assets/9946964/13087647/4766cd34-d4e9-11e5-8f18-47fb4100dfe8.png)

**Comment by BBasile** [comment]
for DUB you have the DUB project inspector, accessible from the __Windows__ menu.
Once you have opened a DUB project, the widget will be unlocked and you be able to open files or edit properties

![dubed](https://cloud.githubusercontent.com/assets/16154339/13088007/c89a7314-d4ea-11e5-9af6-f89d609d0aa6.png)

If you plan to use mostly DUB you can undock the two widgets at the right and put the DUB project inspector instead.

**Comment by BBasile** [comment]
If you want to try with a CE project, clone this one https://github.com/BBasile/dbeaengine and inside the build lib folder there is a file named dbeaengine.coedit whicg is a CE project.

Otherwise for new CE projects you have to add files manually (see https://github.com/BBasile/Coedit/wiki#project-inspector-widget)

for new DUB project, the files wont be detected until you save explicitly the _dub.json_ file, and you'll have to reload the json each time new files are added (or right click in the DUB project editor and click _refresh_).

**Comment by DenianArthurShades** [comment]
Ok... kind of unusual to have separate widgets for the project formats, but I guess it works. Still, thanks!

**Comment by BBasile** [comment]
Plz don't forget to close when you'll get that DUB and CE projects are not displayed in the same widget.
In the meantime I've tagged the issue as invalid.

Thx.
