### ISSUE TITLE
Care to maintain coedit package on AUR?

### ISSUE THREAD

**Issue by agauniyal** [BBasile/Coedit#164]
https://aur.archlinux.org/packages/coedit-bin/ is lying orphan on AUR package repositories and if someone has experience with maintaining such packages and could take this duty, it would help a lot.

Thanks :)

**Comment by BBasile** [comment]
I'm no an ArchLinux user but i suggest to contact @WildN00b (the maintainer of most dlang-related packages), who also handles dcd https://aur.archlinux.org/packages/dcd-git/. coedit is easy to package. two binaries and an icon.

**Comment by BBasile** [comment]
Actually i've detected who is this personn on GH. ping @Vild, are you interested to maintain this AUR package ?

**Comment by Vild** [comment]
I will take a look at that package later, but I can probably maintain it.

**Comment by Vild** [comment]
I've decided to take over the package and I'm in the process of restructuring the PKGBUILD file a bit before pushing.

I'm just wondering if you have thought about using something like [symver](http://semver.org/) instead of "3_update_2" for the version system. The current one shouldn't be any problems what I could see, but it will stand out compared to other package versions.

Should I add all the programs that are referenced here http://bbasile.github.io/Coedit/widgets_about as dependencies?
And if so, do I need to add a version check for them, I could not find anything about this, but I could have missed something.

**Comment by BBasile** [comment]
> I'm just wondering if you have thought about using something like symver

No, semVer is not planned. It could be used but for a software that get half a dozen of release per year semVer is not useful. I have a few commands that do the split for the shell scripts used to make the RPM and the DEB: https://github.com/BBasile/Coedit/blob/master/cesetup/rpm.sh#L1..L4

> Should I add all the programs that are referenced here http://bbasile.github.io/Coedit/widgets_about as dependencies

No, only _DMD >= 2.072_ is necessary but not for DMD itself, rather for the tool _ddemangle_ which is only usable from this version.

> And if so, do I need to add a version check for them, I could not find anything about this, but I could have missed something.

I think i've answered but actually i can confirm that the only place where i do a version check is for dfmt. But again, it's not required.

**Comment by BBasile** [comment]
Okay, i close and i'm glad to see that this was a successful mediation ! Thanks again Vild.
