### ISSUE TITLE
coedit.drivemessagefix.zip

### ISSUE THREAD

**Issue by leh103** [BBasile/Coedit#19]
The coedit.exe in this file does not work in a 32 bit windows 7 environment. It fixes the drive does not have a disk error, but gives an Access Violation error. So I went back to the old one since it worked when you canceled the errors.

It is a shame since I was hoping to run the same editor for the D language in all four of the programming environments I have set up.

And yes my 32 bit Windows 7 computer still has a floppy drive it has had one every since I first built the computer with a pentium I motherboard. I have since changed and upgraded everything in it. I do not use the floppy drive so I should probably remove it. This would not solve the problem since coedit on that machine still gets an error for the DVD drive.

**Comment by BBasile** [comment]
I've checked the new file and it works fine here.
I'm embarrassed to ask you this but are you sure that you system is clean ?

Nobody has ever reported this issue before. I've been using Coedit a lot since the beginning on a win7 32 bit then on the 32 bit sub environment of a win 7 64 bit, with a DVD drive and everything although my config is different since i use several HDD on the same hardware.

Also you could simply disable the floppy drive in the motherboard BIOS if you don't want to open the sarcophagus.

**Comment by BBasile** [comment]
i close and please continue in the previous topic
