### ISSUE TITLE
Slow IDE start

### ISSUE THREAD

**Issue by arietto** [BBasile/Coedit#248]
Coedit (tested on 3.6.3 version)  startup lasts more than 4 seconds on my PC (8 Gb RAM, Intel Pentium G4400 3.30 GHz, SSD  ADATA SP550). Lazarus startup lasts less than 2 seconds. I see **Dfmt commander window**, **DUB project editor**, **CE project editor** creation at the very beginning of Coedit startup. But then I see no   **Dfmt commander window**, **DUB project editor** windows at the end of initialization. I suppose that Coedit initialization is not optimized (perhaps, some windows are created and then destroyed).

**Comment by BBasile** [comment]
I don't know what is happening. I've made a video today where i make a fresh setup today (see https://github.com/BBasile/Coedit/issues/249) and you can see that it starts almost immediately.
My real setup is slower because more library paths are scanned at the beginning but it shouldn't be your case if you just have setup.

**Comment by BBasile** [comment]
You can try to start dcd-server manually and then start the IDE (will cause symbol cache and scanning), then close the IDE, then start it again (no need for caching the second time). It will give a hint saying if your slowdown is caused by DCD.

**Comment by BBasile** [comment]
It might be are slow down caused by your antivirus software.
