### ISSUE TITLE
"JumpToDeclaration" and "Find next" can both be assigned F3.

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#311]
When this is done, Find next takes precedence. The duplicate assignment logic should prevent this.

**Comment by BBasile** [comment]
I'm gonna close this because this is not really a bug. shortcuts are dispatched to the different widgets and might be handled or not, depending on certain conditions (for example when an action is enabled the dispatching will stop and other components cant use it and to the opposite when the same action is disabled the shortcut will be dispatched further).

Duplicate assignment only works within a same category and it can be legit to use the same shortcut in two different contexts, even if it's true that this can fail.

**Comment by BBasile** [comment]
Yes, maybe this can be done
