### ISSUE TITLE
Warnings for unsued variables

### ISSUE THREAD

**Issue by BennD** [BBasile/Coedit#358]
Hi,
i found out that you get a warning for unused variable, if you leave out the () after a function call.

```
void main()
{
    import std.stdio : writeln;

    const int testValue; // warning for never used variable
    testValue.writeln; // if you write testValue.writeln() instead, you get no warning.
}
```

Are little issues like this wanted?

**Comment by BBasile** [comment]
> Are little issues like this wanted?

Yes of course report what you want.

The basic problem here comes from [D-Scanner](https://github.com/dlang-community/D-Scanner), which is not perfect due to the fact that D is a complex language. For instance here the problem is that CTFE is not handled by D-Scanner. The linter thinks that `testValue` is an agreggate (struct or class).

I'll report to D-Scanner however because i see a pattern of something that can be eventually fixed (since at the local scope `testValue` is known.

**Comment by BBasile** [comment]
Latest D-Scanner release includes a fix. I recommend to update the tools once the announce will be published in the News Group, planned tomorrow, by tools i mean D-Scanner and also DCD, especially if you (non nominative) are still using a version <= 0.9.11.
