### ISSUE TITLE
Shift+Space

### ISSUE THREAD

**Issue by Kelet** [BBasile/Coedit#38]
Hi There,

Coedit is now my IDE of voice for my D language projects. It's interesting to see Lazarus being used, as I always thought it was an awesome ecosystem for cross-platform projects.

In most editors, when I press shift+space, it defaults to making a space. There are many situations where this happens (accidentally) and is a slight annoyance to me. Is this because it's reserved for a key-binding, and is there any way to change the behavior of shift+space => insert space?

Regards,
Kelet

**Comment by BBasile** [comment]
Yes by default Shift+Space is assigned to the _static macros_. Actually this shortcut does nothing since static macros are (by default) inserted automatically. You can clear the shortcut in options editor, category _Static macros_. If it's not assigned somewhere else It may insert a space. (to be verified).

**Comment by Kelet** [comment]
Ah thank-you @BBasile, I figured it was something like that. I appreciate the explanation!
