### ISSUE TITLE
Issue with Anchor Docking

### ISSUE THREAD

**Issue by ooptimum** [BBasile/Coedit#4]
##### Steps to reproduce the bug
1. Run coedit.exe with the default layout (i.e. delete docking.xml)
2. Tear all widgets off the main window by dragging them out
3. Whoops! You can't dock them back in the main window!

However, you can dock all widgets back to the main window upon application restart.

Tested with Lazarus 1.4.0, LCL 1.4.0.4, Win32

**Comment by BBasile** [comment]
Confirmed, however since the docking is managed by a third party library, i'll relay the repport to the author.

**Comment by BBasile** [comment]
a few weeks ago some code has been added to prevent Coedit to save any invalid layout (there are other bugs with the feature, it's more global). This is the best that could be done. However the problem won't fall into a black hole, it's well noted somewhere in a list. 

I'll also add a note about this in the wiki.

**Comment by BBasile** [comment]
The problem is fixed in 568c229 :grin:. 
I'll release 1_update_1 in Jully. In the meantime, don't close a docked widget using the button in the header. Instead: 
- in a first time right click the header, click the menu item _undock_. 
- then at this time, when it's undocked, you can close the widget.

This is really the best that can be done in Coedit 1. The problem is that the fixes i could make to the 3rd party component are only visible when the 3rd party component is itself released...so 3 times per year. Hopefully the 3rd party thing is OSS so it could be even worst (not to name _D....i_ :speak_no_evil:)

**Comment by BBasile** [comment]
the fix is applied in version 1 update 1

https://github.com/BBasile/Coedit/releases/tag/1_update_1
